"use strict";
exports.__esModule = true;
var express_1 = require("express");
var router = express_1["default"].Router();
var auth_controller_1 = require("../controllers/auth.controller");
var local_variables_1 = require("../middlewares/local-variables");
var verifyUser_1 = require("../middlewares/verifyUser");
router.post("/login", auth_controller_1.login);
router.post("/register", auth_controller_1.register);
router.get("/generateOTP", verifyUser_1.verifyUser, local_variables_1["default"], auth_controller_1.generateOTP);
router.get("/verifyOTP", verifyUser_1.verifyUser, auth_controller_1.verifyOTP);
router.get("/create-reset-session", auth_controller_1.createResetSession);
router.put("/reset-password", verifyUser_1.verifyUser, auth_controller_1.resetPassword);
exports["default"] = router;
